ALTER TABLE "Business"
ADD COLUMN "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "bannerPhotoUrl" TEXT,
ADD COLUMN "logoUrl" TEXT,
ADD COLUMN "brandColor" TEXT NOT NULL DEFAULT '#0f766e';
