const text: {
  [key: string]: {
    [key: string]: string;
  };
} = {
  en: {
    information: "Information",
    address: "Address",
    progressiveDiscount: "Progressive Discount",
    learnMore: "Learn more",
    myCart: "My Cart",
    buyMore: "Buy More, Save More",
    addMore:
      "Add more pizzas, sfihas, or drinks to unlock better savings. Spend $60 or more and get a special prize on us.",
    orderNow: "Order Now!",
    delivery: "Delivery",
    hoursOfOperation: "Hours of operation",
    sunday: "sunday",
    monday: "monday",
    tuesday: "tuesday",
    wednesday: "wednesday",
    thursday: "thursday",
    friday: "friday",
    saturday: "saturday",
    add: "Add",
    comments: "Comments",
    optional: "Optional",
    back: "Back",
    change: "Change",
    selectService: "Select service type",
    takeAway: "Take Away",
    yourCart: "Your cart is empty",
    backToMenu: "Back to menu",
    loading: "Loading...",
    cartSummary: "Cart summary",
    subtotal: "Subtotal",
    subtotalProducts: "Subtotal products",
    totalProducts: "Total products",
    discount: "Discount",
    totalLabel: "TOTAL",
    deliveryFee: "delivery fee",
    salesTax: "Sales tax",
    tax: "Tax",
    total: "Total",
    billSummary: "Bill summary",
    products: "products",
    yourProducts: "Your products",
    modifiers: "Modifiers",
    tip: "Tip",
    view: "View",
    verify: "Verify",
    deliveryAddress: "Delivery address",
    noAddress: "No address added",
    addNew: "Add new address",
    paymentMethod: "Payment method",
    cash: "Cash",
    card: "Card",
    zelle: "Zelle",
    addAddress: "Add address",
    numberAppartment: "Number + Appartment",
    reference: "Reference",
    confirmAddress: "Confirm address",
    confirm: "Confirm",
    validPhone: "Insert a valid phone",
    insertName: "Insert you name",
    selectAddress: "Select an address",
    yourName: "Your name",
    phone: "Phone",
    date: "Date",
    time: "Time",
    scheduleDateTime: "Date and time",
    scheduleOrder: "Store currently closed",
    chatOnWhatsapp: "Chat on WhatsApp",
    inquireAboutYourOrder: "Inquire about your order",
    pendingOrderAlert: "Working on your order",
    orderReceived: "Order received!",
    paymentInfo: "Payment info",
    accepted: "Accepted",
    preparing: "Preparing",
    ready: "Ready",
    outForDelivery: "Out for delivery",
    delivered: "Delivered",
    refreshStatus: "Refresh status",
    viewOrder: "View order",
    orderForLater: "Schedule order",
    open: "Open",
    closed: "Closed",
    selectDate: "Select a date",
    selectTime: "Select a time",
    selectDateAndTime: "Select a date and time",
    chooseAvailableDate: "Choose an available day",
    chooseAvailableTime: "Choose an available time",
    noScheduleAvailability: "No schedule available in the next 7 days",
    outsideCoverageArea: "This address is outside our delivery area",
    addressSaveError: "We couldn't save this address",
    won: "Won",
    chooseYourPrize: "Choose your prize",
    choosePrizeModalTitle: "Choose you prize",
    selectPrizeToContinue: "Select a prize to continue",
    prizeSelection: "Prize selection",
    prizeRequired: "Pick a prize before selecting delivery or take away",
    quantityShort: "Qty",
    homeDelivery: "Home delivery from",
    deliveryPrice: 'The delivery price will be calculated based on your location.',
    takeaway: 'Take Away',
    deliveryMinimum: "Delivery available from",
    checkoutError: "We could not place your order. Please try again.",
    verifyPickup: "Verify pickup instructions",
    verifyPickupModalTitle: "How to pick up your order",
    verifyPickupStep1Title: "Check your order number",
    verifyPickupStep1Description:
      "Use the order number shown on your confirmation screen.",
    verifyPickupStep2Title: "Go to the pickup counter",
    verifyPickupStep2Description:
      "Come to Zaatar Grill & Pizza and head to the pickup area.",
    verifyPickupStep3Title: "Confirm and collect",
    verifyPickupStep3Description:
      "Show your order number to our team and collect your order.",
    verifyPickupDone: "Got it",
  },
  pt: {
    information: "Informações",
    address: "Endereço",
    progressiveDiscount: "Desconto progressivo",
    learnMore: "Saiba mais",
    myCart: "Meu carrinho",
    buyMore: "Compre mais, economize mais",
    addMore:
      "Adicione mais pizzas, esfihas ou bebidas para desbloquear melhores descontos. Gaste $60 ou mais e ganhe um brinde especial.",
    orderNow: "Peça agora!",
    delivery: "Entrega",
    hoursOfOperation: "Horário de funcionamento",
    sunday: "domingo",
    monday: "segunda-feira",
    tuesday: "terça-feira",
    wednesday: "quarta-feira",
    thursday: "quinta-feira",
    friday: "sexta-feira",
    saturday: "sábado",
    add: "Adicionar",
    comments: "Observações",
    optional: "Opcional",
    back: "Voltar",
    change: "Alterar",
    selectService: "Selecione o tipo de serviço",
    takeAway: "Retirada",
    yourCart: "Seu carrinho está vazio",
    backToMenu: "Voltar ao cardápio",
    loading: "Carregando...",
    cartSummary: "Resumo do pedido",
    subtotal: "Subtotal",
    subtotalProducts: "Subtotal produtos",
    totalProducts: "Total produtos",
    discount: "Desconto",
    totalLabel: "TOTAL",
    deliveryFee: "taxa de entrega",
    salesTax: "Imposto sobre vendas",
    tax: "Imposto",
    total: "Total",
    billSummary: "Resumo da conta",
    products: "produtos",
    yourProducts: "Seus produtos",
    modifiers: "Modificadores",
    tip: "Gorjeta",
    view: "Ver",
    verify: "Verificar",
    deliveryAddress: "Endereço de entrega",
    noAddress: "Nenhum endereço cadastrado",
    addNew: "Adicionar novo endereço",
    paymentMethod: "Forma de pagamento",
    cash: "Dinheiro",
    card: "Cartão",
    zelle: "Zelle",
    addAddress: "Adicionar endereço",
    numberAppartment: "Número + Apto",
    reference: "Referência",
    confirmAddress: "Confirmar endereço",
    confirm: "Confirmar",
    validPhone: "Insira um telefone válido",
    insertName: "Insira seu nome",
    selectAddress: "Selecione um endereço",
    yourName: "Seu nome",
    phone: "Telefone",
    date: "Data",
    time: "Horário",
    scheduleDateTime: "Data e horário",
    scheduleOrder: "Agende seu pedido",
    chatOnWhatsapp: "Falar no WhatsApp",
    inquireAboutYourOrder: "Falar sobre seu pedido",
    pendingOrderAlert: "Preparando seu pedido",
    orderReceived: "Pedido recebido!",
    paymentInfo: "Pagamento",
    accepted: "Aceito",
    preparing: "Preparando",
    ready: "Pronto",
    outForDelivery: "Saiu para entrega",
    delivered: "Entregue",
    refreshStatus: "Atualizar status",
    viewOrder: "Ver pedido",
    orderForLater: "Peça para depois",
    open: "Aberto",
    closed: "Fechado",
    selectDate: "Selecione uma data",
    selectTime: "Selecione um horário",
    selectDateAndTime: "Selecione uma data e horário",
    chooseAvailableDate: "Escolha um dia disponível",
    chooseAvailableTime: "Escolha um horário disponível",
    noScheduleAvailability: "Sem horários disponíveis nos próximos 7 dias",
    outsideCoverageArea: "Este endereço está fora da nossa área de entrega",
    addressSaveError: "Nao foi possivel salvar este endereco",
    won: "Você ganhou",
    chooseYourPrize: "Escolha seu prêmio",
    choosePrizeModalTitle: "Escolha seu prêmio",
    selectPrizeToContinue: "Selecione um prêmio para continuar",
    prizeSelection: "Seleção de prêmio",
    prizeRequired: "Escolha um prêmio antes de selecionar entrega ou retirada",
    quantityShort: "Qtd",
    deliveryMinimum: "Entrega disponível a partir de",
    checkoutError: "Nao foi possivel concluir seu pedido. Tente novamente.",
    verifyPickup: "Verificar instruções de retirada",
    verifyPickupModalTitle: "Como retirar seu pedido",
    verifyPickupStep1Title: "Confira o número do pedido",
    verifyPickupStep1Description:
      "Use o número do pedido mostrado na tela de confirmação.",
    verifyPickupStep2Title: "Vá ao balcão de retirada",
    verifyPickupStep2Description:
      "Chegue ao Zaatar Grill & Pizza e vá para a área de retirada.",
    verifyPickupStep3Title: "Confirme e retire",
    verifyPickupStep3Description:
      "Mostre o número do pedido para nossa equipe e retire seu pedido.",
    verifyPickupDone: "Entendi",
  },
  es: {
    information: "Información",
    address: "Dirección",
    progressiveDiscount: "Descuento progresivo",
    learnMore: "Saber más",
    myCart: "Mi carrito",
    buyMore: "Compra más, ahorra más",
    addMore:
      "Agrega más pizzas, sfihas o bebidas para desbloquear mejores ahorros. Gasta $60 o más y recibe un premio especial de nuestra parte.",
    orderNow: "Ordena ahora",
    delivery: "Entrega",
    hoursOfOperation: "Horario de atención",
    sunday: "domingo",
    monday: "lunes",
    tuesday: "martes",
    wednesday: "miércoles",
    thursday: "jueves",
    friday: "viernes",
    saturday: "sábado",
    add: "Agregar",
    comments: "Comentarios",
    optional: "Opcional",
    back: "Volver",
    change: "Cambiar",
    selectService: "Selecciona el tipo de servicio",
    takeAway: "Para llevar",
    yourCart: "Tu carrito está vacío",
    backToMenu: "Volver al menú",
    loading: "Cargando...",
    cartSummary: "Resumen del carrito",
    subtotal: "Subtotal",
    subtotalProducts: "Subtotal productos",
    totalProducts: "Total productos",
    discount: "Descuento",
    totalLabel: "TOTAL",
    deliveryFee: "tarifa de entrega",
    salesTax: "Impuesto sobre ventas",
    tax: "Impuesto",
    total: "Total",
    billSummary: "Resumen de la cuenta",
    products: "productos",
    yourProducts: "Tus productos",
    modifiers: "Modificadores",
    tip: "Propina",
    view: "Ver",
    verify: "Verificar",
    deliveryAddress: "Dirección de entrega",
    noAddress: "No hay dirección agregada",
    addNew: "Agregar nueva dirección",
    paymentMethod: "Método de pago",
    cash: "Efectivo",
    card: "Tarjeta",
    zelle: "Zelle",
    addAddress: "Agregar dirección",
    numberAppartment: "Número + Apartamento",
    reference: "Referencia",
    confirmAddress: "Confirmar dirección",
    confirm: "Confirmar",
    validPhone: "Ingresa un teléfono válido",
    insertName: "Ingresa tu nombre",
    selectAddress: "Selecciona una dirección",
    yourName: "Tu nombre",
    phone: "Teléfono",
    date: "Fecha",
    time: "Hora",
    scheduleDateTime: "Fecha y hora",
    scheduleOrder: "Tienda cerrada actualmente",
    chatOnWhatsapp: "Chatear en WhatsApp",
    inquireAboutYourOrder: "Consultar sobre tu pedido",
    pendingOrderAlert: "Estamos preparando tu pedido",
    orderReceived: "¡Pedido recibido!",
    paymentInfo: "Información de pago",
    accepted: "Aceptado",
    preparing: "Preparando",
    ready: "Listo",
    outForDelivery: "En camino",
    delivered: "Entregado",
    refreshStatus: "Actualizar estado",
    viewOrder: "Ver pedido",
    orderForLater: "Programar pedido",
    open: "Abierto",
    closed: "Cerrado",
    selectDate: "Selecciona una fecha",
    selectTime: "Selecciona una hora",
    selectDateAndTime: "Selecciona fecha y hora",
    chooseAvailableDate: "Elige un día disponible",
    chooseAvailableTime: "Elige una hora disponible",
    noScheduleAvailability: "No hay horarios disponibles en los próximos 7 días",
    outsideCoverageArea: "Esta dirección está fuera de nuestra zona de entrega",
    addressSaveError: "No pudimos guardar esta dirección",
    won: "Ganaste",
    chooseYourPrize: "Elige tu premio",
    choosePrizeModalTitle: "Elige tu premio",
    selectPrizeToContinue: "Selecciona un premio para continuar",
    prizeSelection: "Selección de premio",
    prizeRequired: "Elige un premio antes de seleccionar entrega o para llevar",
    quantityShort: "Cant.",
    homeDelivery: "Entrega a domicilio desde",
    deliveryPrice: "El precio de entrega se calculará según tu ubicación.",
    takeaway: "Para llevar",
    deliveryMinimum: "Entrega disponible desde",
    checkoutError: "No pudimos completar tu pedido. Inténtalo de nuevo.",
    verifyPickup: "Ver instrucciones de recogida",
    verifyPickupModalTitle: "Cómo recoger tu pedido",
    verifyPickupStep1Title: "Revisa tu número de pedido",
    verifyPickupStep1Description:
      "Usa el número de pedido que aparece en la pantalla de confirmación.",
    verifyPickupStep2Title: "Ve al mostrador de recogida",
    verifyPickupStep2Description:
      "Llega a Zaatar Grill & Pizza y dirígete al área de recogida.",
    verifyPickupStep3Title: "Confirma y recoge",
    verifyPickupStep3Description:
      "Muestra tu número de pedido a nuestro equipo y recoge tu pedido.",
    verifyPickupDone: "Entendido",
  },
};

export default text;
