const text: {
  [key: string]: {
    [key: string]: string;
  };
} = {
  en: {
    information: "Information",
    address: "Address",
    progressiveDiscount: "Progressive Discount",
    learnMore: "Learn more",
    myCart: "My Cart",
    buyMore: "Buy More, Save More",
    addMore:
      "Add more pizzas, sfihas, or drinks to unlock better savings. Spend $60 or more and get a special prize on us.",
    orderNow: "Order Now!",
    delivery: "Delivery",
    hoursOfOperation: "Hours of operation",
    sunday: "sunday",
    monday: "monday",
    tuesday: "tuesday",
    wednesday: "wednesday",
    thursday: "thursday",
    friday: "friday",
    saturday: "saturday",
    add: "Add",
    comments: "Comments",
    optional: "Optional",
    back: "Back",
    selectService: "Select service type",
    takeAway: "Take Away",
    yourCart: "Your cart is empty",
    backToMenu: "Back to menu",
    loading: "Loading...",
    cartSummary: "Cart summary",
    subtotal: "Subtotal",
    subtotalProducts: "Subtotal products",
    totalProducts: "Total products",
    totalLabel: "TOTAL",
    deliveryFee: "delivery fee",
    tax: "Tax",
    total: "Total",
    billSummary: "Bill summary",
    products: "products",
    yourProducts: "Your products",
    tip: "Tip",
    view: "View",
    verify: "Verify",
    deliveryAddress: "Delivery address",
    noAddress: "No address added",
    addNew: "Add new address",
    paymentMethod: "Payment method",
    cash: "Cash",
    card: "Card",
    zelle: "Zelle",
    addAddress: "Add address",
    numberAppartment: "Number + Appartment",
    reference: "Reference",
    confirmAddress: "Confirm address",
    confirm: "Confirm",
    validPhone: "Insert a valid phone",
    insertName: "Insert you name",
    selectAddress: "Select an address",
    yourName: "Your name",
    phone: "Phone",
    date: "Date",
    time: "Time",
    scheduleDateTime: "Date and time",
    scheduleOrder: "Store currently closed",
    chatOnWhatsapp: "Chat on WhatsApp",
    inquireAboutYourOrder: "Inquire about your order",
    pendingOrderAlert: "Working on your order",
    orderReceived: "Order received!",
    paymentInfo: "Payment info",
    accepted: "Accepted",
    preparing: "Preparing",
    ready: "Ready",
    outForDelivery: "Out for delivery",
    delivered: "Delivered",
    refreshStatus: "Refresh status",
    viewOrder: "View order",
    orderForLater: "Schedule a time to place your order",
    open: "Open",
    closed: "Closed",
    selectDate: "Select a date",
    selectTime: "Select a time",
    selectDateAndTime: "Select a date and time",
    chooseAvailableDate: "Choose an available day",
    chooseAvailableTime: "Choose an available time",
    noScheduleAvailability: "No schedule available in the next 7 days",
    outsideCoverageArea: "This address is outside our delivery area",
    addressSaveError: "We couldn't save this address",
  },
  pt: {
    information: "Informações",
    address: "Endereço",
    progressiveDiscount: "Desconto progressivo",
    learnMore: "Saiba mais",
    myCart: "Meu carrinho",
    buyMore: "Compre mais, economize mais",
    addMore:
      "Adicione mais pizzas, esfihas ou bebidas para desbloquear melhores descontos. Gaste $60 ou mais e ganhe um brinde especial.",
    orderNow: "Peça agora!",
    delivery: "Entrega",
    hoursOfOperation: "Horário de funcionamento",
    sunday: "domingo",
    monday: "segunda-feira",
    tuesday: "terça-feira",
    wednesday: "quarta-feira",
    thursday: "quinta-feira",
    friday: "sexta-feira",
    saturday: "sábado",
    add: "Adicionar",
    comments: "Observações",
    optional: "Opcional",
    back: "Voltar",
    selectService: "Selecione o tipo de serviço",
    takeAway: "Retirada",
    yourCart: "Seu carrinho está vazio",
    backToMenu: "Voltar ao cardápio",
    loading: "Carregando...",
    cartSummary: "Resumo do pedido",
    subtotal: "Subtotal",
    subtotalProducts: "Subtotal produtos",
    totalProducts: "Total produtos",
    totalLabel: "TOTAL",
    deliveryFee: "taxa de entrega",
    tax: "Imposto",
    total: "Total",
    billSummary: "Resumo da conta",
    products: "produtos",
    yourProducts: "Seus produtos",
    tip: "Gorjeta",
    view: "Ver",
    verify: "Verificar",
    deliveryAddress: "Endereço de entrega",
    noAddress: "Nenhum endereço cadastrado",
    addNew: "Adicionar novo endereço",
    paymentMethod: "Forma de pagamento",
    cash: "Dinheiro",
    card: "Cartão",
    zelle: "Zelle",
    addAddress: "Adicionar endereço",
    numberAppartment: "Número + Apto",
    reference: "Referência",
    confirmAddress: "Confirmar endereço",
    confirm: "Confirmar",
    validPhone: "Insira um telefone válido",
    insertName: "Insira seu nome",
    selectAddress: "Selecione um endereço",
    yourName: "Seu nome",
    phone: "Telefone",
    date: "Data",
    time: "Horário",
    scheduleDateTime: "Data e horário",
    scheduleOrder: "Agende seu pedido",
    chatOnWhatsapp: "Falar no WhatsApp",
    inquireAboutYourOrder: "Falar sobre seu pedido",
    pendingOrderAlert: "Preparando seu pedido",
    orderReceived: "Pedido recebido!",
    paymentInfo: "Pagamento",
    accepted: "Aceito",
    preparing: "Preparando",
    ready: "Pronto",
    outForDelivery: "Saiu para entrega",
    delivered: "Entregue",
    refreshStatus: "Atualizar status",
    viewOrder: "Ver pedido",
    orderForLater: "Peça para depois",
    open: "Aberto",
    closed: "Fechado",
    selectDate: "Selecione uma data",
    selectTime: "Selecione um horário",
    selectDateAndTime: "Selecione uma data e horário",
    chooseAvailableDate: "Escolha um dia disponível",
    chooseAvailableTime: "Escolha um horário disponível",
    noScheduleAvailability: "Sem horários disponíveis nos próximos 7 dias",
    outsideCoverageArea: "Este endereço está fora da nossa área de entrega",
    addressSaveError: "Nao foi possivel salvar este endereco",
  },
};

export default text;
